[project]
name = "tmdb-cli-tool"
version = "0.1.0"
description = "A CLI for The Movie Database"
authors = [{ name = "Mehmet Emre Cebeci" }]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "requests",
    "python-dotenv"
]

[project.scripts]
tmdb-app = "tmdb_app.main:main"
